### ISSUE TITLE
Q

### ISSUE THREAD

**Issue by panicwq** [ColumbiaDVMM/AutoGAN#1]
Excuse me, will the code of your paper be published on github? 
I am looking forward to it, thank you.

**Comment by spongezhang** [comment]
Hi,

Our paper just got accepted by WIFS. We will release the code while preparing our final version of the paper. It should be here within 2-3 weeks. Would you please share your email address with us? We will send you a notice once the code is ready. 

Best,
Xu

**Comment by spongezhang** [comment]
The code is ready. Sorry for the delay.
