### ISSUE TITLE
Hello, can you give me the original picture of of these two face images

### ISSUE THREAD

**Issue by wanzuliang** [ColumbiaDVMM/AutoGAN#10]
Hello, Thanks for your work.I want to use your sample picture to do some experiments, can you give me a copy of the original picture of of these two face images?
I want to study the difference between real and fake faces。
![checkerboard](https://user-images.githubusercontent.com/7219312/114290829-ed3e3580-9ab4-11eb-9068-dd3166499352.png)

**Comment by spongezhang** [comment]
Hi,

Since I've already left Columbia University for quite some time. I have difficulty finding the original copy of the images. This special sample pair is coming from StarGAN. I believe you can find similar pair easily in the StarGAN example. Will this help?

Best,
Xu

**Comment by wanzuliang** [comment]
Thanks for your reply, your answer is very helpful.
