### ISSUE TITLE
There is no autogan folder..

### ISSUE THREAD

**Issue by seungkee** [ColumbiaDVMM/AutoGAN#4]

**Comment by spongezhang** [comment]
Did you run a full recursive clone to make sure you get all the submodules?
git clone --recursive git@github.com:ColumbiaDVMM/AutoGAN.git

**Comment by 0x80000000** [comment]
The command gives me following error,

git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by seungkee** [comment]
The command gives me following error,

git@github.com: Permission denied (publickey)
fatal: Could not read from remote repository.

**Comment by seungkee** [comment]
And If I just clone from github page, there is no autogan folder..

**Comment by spongezhang** [comment]
Try this, git clone --recursive https://github.com/ColumbiaDVMM/AutoGAN.git

**Comment by seungkee** [comment]
Yep clone worked. 
still I can't find autogan folder and prepare_data.py which are described on README.md as follows.

Download cycleGAN image data.
cd autogan
python datasets/prepare_data.py

**Comment by seungkee** [comment]
I mean, I can find discriminator code in repository but can't find generator code.

**Comment by carlini** [comment]
I observe the same effect. I am cloning with --recursivebut get no autogan folder (or datasets).

**Comment by amandhamija98** [comment]
I cant find datasets/prepare_data.py. I have cloned recursively. This is not present on the github repo either. Could someone please help me out

**Comment by spongezhang** [comment]
Dear all,

Sorry for the delayed reply. I was completely overwhelmed by COVID-19 during the past 2 months. 

The issue is clearly due to I wrongly setting up my git submodule. The problem should be fixed. Please make a recursive clone and see whether it works for you or not.

Thank you for your interests and sorry again for the delayed solution. 

Best,
Xu

**Comment by spongezhang** [comment]
No further comment, close the issue.
