### ISSUE TITLE
Syntax error in code/run_test.py; missing close square bracket

### ISSUE THREAD

**Issue by carlini** [ColumbiaDVMM/AutoGAN#5]
The file code/run_test.py has a syntax error and is missing a close square bracket:

```python
elif args.dataset == 'AutoGAN':
    datasets = ['horse_auto', 'zebra_auto', 'summer_auto', 'winter_auto', 'apple_auto', 'orange_auto', 'facades_auto', 'cityscapes_auto', 'satellite_auto', 'ukiyoe_auto', 'vangogh_auto', 'cezanne_auto', 'monet_auto', 'photo_auto',
else:
```

How is this line supposed to end? For now I've just ended it after the final comma.

**Comment by spongezhang** [comment]
Thanks for the checking. I fixed the code. It's true, there is a missing bracket.
