### ISSUE TITLE
conda environment fails

### ISSUE THREAD

**Issue by jmaba** [ColumbiaDVMM/AutoGAN#7]
Hello,

When installing the conda env it fails (for e.g. intel package is not found, conflicts etc).

Do you have another yml file? 
Maybe a docker image - or some enviroment details you have - like linux version, python version, conda version.

Adrian

**Comment by spongezhang** [comment]
Emm. I think I'm using linux 16.04 with python3.7 + anaconda 4.*

Can you be more specific about which package is miss and what's the conflicts are?

I don't have a docker image. I may be able to generate a pip requirement.txt file if that helps. Conda env seems more stable for me. 

I think you can safely remove the missing package and remove the subversions number of the conflicted packages in the yml file.

Another solution is not to use the yml file and start with your env with pytorch and to install the missing packages raised when you run the code. It shouldn't be very complicated. 

Best,
Xu

**Comment by jmaba** [comment]
Hello,

Thanks for the very fast answer. I will do that (manually start with PyTorch).
Just another short question if possible - prepare_model - I can't find.

Kind regards,
Adrian

**Comment by spongezhang** [comment]
Good catch. The script is somehow missing. :( It does nothing but download cycleGAN models. Please follow the new readme and use download_cyclegan_model.sh from CycleGAN to download the models. 

Let me know if you have any other issues.

**Comment by jmaba** [comment]
All your suggestions work. I will close this now
